[tools]
deno = "2.8.1"
go = "1.24"
tinygo = "0.41.1"


[tasks.build]
run = """
  # build binary
  GOOS=js GOARCH=wasm tinygo build -o ./app.wasm ./main.go

  # copy wasm_exec.js to ./bin
  cp $(tinygo env TINYGOROOT)/targets/wasm_exec.js ./wasm_exec.js
  # it's necessary to remove this line or the worker breaks
  sed -i 's/global\\.require = require;//g' ./wasm_exec.js
"""
